version: 0.2

phases:
  install:
      - npm install
  build:
    commands:
      - |
        npx hardhat node &
        npx hardhat compile
        npx hardhat run scripts/sample-script.js --network localhost
artifacts:
  files:
    - 'src/artifacts/*'