version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - |
        npx hardhat node &
        npx hardhat compile
        npx hardhat run scripts/sample-script.js --network localhost >> .env
artifacts:
  files:
    - '**/*'
  base-directory: 'src/artifacts'